### ISSUE TITLE
Some Question

### ISSUE THREAD

**Issue by SoakDog** [anse3832/IQT#1]
Hi，I have questions about some codes in train.py

I would like to ask in transforms.Compose, why is Normalize before ToTensor()?
Shouldn't Normalize be after ToTensor()？

**Comment by anse3832** [comment]
I intended Normalize() to work on numpy array, so I call Normalize() before ToTensor().
Normalize() also seems to work on torch tensor, but I didn't tried it.
( Normalize() is implemented in ./utils/util.py, so please check the code )

**Comment by SoakDog** [comment]
> 

Thanks for the reply, I have figured it out after reading the code.
