### ISSUE TITLE
could you please tell me How should I solve this problem?

### ISSUE THREAD

**Issue by 870715478** [anse3832/IQT#3]
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

Can datasets be used directly? Need to deal with it? Like the format or something?

**Comment by ferryfarhan14** [comment]
I have the same problem

**Comment by anse3832** [comment]
> cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
> 
> Can datasets be used directly? Need to deal with it? Like the format or something?

**Comment by anse3832** [comment]
Maybe the error comes from cv2.imread function.
You have to check if the image file you want to load is correct path.
